### PR TITLE
added Memory4gb, updated deprecated emscripten arguments, updated package.json dependencies

### PR DESCRIPTION
**Pull request by vegarringdal**
* update package.json dependencies
* update emscripten commands
 * added `-s MAXIMUM_MEMORY=4GB`
   *  Now my biggest IFC loads when I try it with `npm run dev` :-)
 * updated deprecated arguments
 
 More info about deprecated arguments
 `
em++: warning: please replace -g4 with -gsource-map [-Wdeprecated]`
`em++: warning: EXTRA_EXPORTED_RUNTIME_METHODS is deprecated, please use EXPORTED_RUNTIME_METHODS instead [-Wdeprecated]`

### CODE REVIEW

**Comment by vegarringdal** [comment]
Noticed one of my commits had a typo on commands, woops :-) 
Should have been arguments, but guess you squash it anyways if you want it.

**Comment by agviegas** [comment]
Indeed, this works! Very nice work @vegarringdal!
image

**Comment by vegarringdal** [comment]
@agviegas 
If you have multiple files for that building, you can select all files on the file open in that sample, and it will load all

**Comment by agviegas** [comment]
Unfortunately it's not a public model, but it confirms that this work. Very cool!

**Comment by tomvandig** [comment]
Nice!

**Pull request merged**
